# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_placed_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18order_placed_event.proto\x12\x06orders"N\n\x0bOrderPlaced\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x62\x06proto3'
)


_ORDERPLACED = DESCRIPTOR.message_types_by_name["OrderPlaced"]
OrderPlaced = _reflection.GeneratedProtocolMessageType(
    "OrderPlaced",
    (_message.Message,),
    {
        "DESCRIPTOR": _ORDERPLACED,
        "__module__": "order_placed_event_pb2"
        # @@protoc_insertion_point(class_scope:orders.OrderPlaced)
    },
)
_sym_db.RegisterMessage(OrderPlaced)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _ORDERPLACED._serialized_start = 36
    _ORDERPLACED._serialized_end = 114
# @@protoc_insertion_point(module_scope)
